import { notFound, ok } from "./workspace-operations-part-002"
import { ArticleBlock, defaultVisualBlockData, serializeVisualBlockBody, VisualBlockData, VisualBlockKind, WorkspaceOperationResult } from "./workspace-operations-part-001"
export * from "./workspace-operations-part-038"

export const listMcpToolCapabilities = () =>
    ok({
        tools: [
            { name: "list_notebooks", description: "List notebooks owned by user." },
            { name: "read_notebook", description: "Read notebook with ordered page/topic/view tree." },
            { name: "read_workspace", description: "Read workspace summary with totals." },
            { name: "resolve_notebook", description: "Resolve notebook by id or title." },
            { name: "resolve_page", description: "Resolve page by id or title." },
            { name: "resolve_topic", description: "Resolve topic by id or title." },
            { name: "resolve_view", description: "Resolve view by id or title." },
            { name: "list_pages", description: "List pages with topic and view counts." },
            { name: "read_page", description: "Read page and child topics." },
            { name: "create_notebook", description: "Create notebook." },
            { name: "rename_notebook", description: "Rename or mutate notebook metadata." },
            { name: "delete_notebook", description: "Delete notebook and all descendants." },
            { name: "duplicate_notebook", description: "Duplicate a notebook and descendants." },
            { name: "create_page", description: "Create page inside notebook." },
            { name: "rename_page", description: "Rename and/or reorder a page." },
            { name: "reorder_pages", description: "Reorder pages inside notebook." },
            { name: "move_page_to_notebook", description: "Move page across notebooks." },
            { name: "delete_page", description: "Delete page and descendants." },
            { name: "create_topic", description: "Create topic in page." },
            { name: "rename_topic", description: "Rename and/or reorder a topic." },
            { name: "reorder_topics", description: "Reorder topics in page." },
            { name: "move_topic_to_page", description: "Move topic across pages." },
            { name: "duplicate_topic", description: "Duplicate topic and descendant views." },
            { name: "delete_topic", description: "Delete topic and descendant views." },
            { name: "create_view", description: "Create view in topic." },
            { name: "create_view_from_template", description: "Create view from template." },
            { name: "rename_view", description: "Rename or repurpose a view." },
            { name: "change_view_mode", description: "Change view mode." },
            { name: "reorder_views", description: "Reorder views in topic." },
            { name: "move_view_to_topic", description: "Move view across topics." },
            { name: "duplicate_view", description: "Duplicate view content to same/another topic." },
            { name: "delete_view", description: "Delete a view." },
            { name: "create_article", description: "Create/reuse notebook->page->topic->view path and set content." },
            { name: "read_article", description: "Read article with block metadata." },
            { name: "read_view_as_markdown", description: "Read a single view rendered as markdown." },
            { name: "read_view_as_blocks", description: "Read article as parsed blocks." },
            { name: "replace_article_content", description: "Replace article markdown." },
            { name: "insert_article_blocks", description: "Insert parsed blocks into article." },
            { name: "replace_article_block", description: "Replace one block in an article." },
            { name: "remove_article_block", description: "Remove one block in an article." },
            { name: "move_article_block", description: "Move article block." },
            { name: "patch_article_section", description: "Replace section under heading." },
            { name: "apply_article_patch", description: "Apply a small set of article block operations." },
            { name: "lint_article", description: "Validate article parser round-trip and references." },
            { name: "upsert_visual_block", description: "Insert or replace a visual article block." },
            { name: "remove_visual_block", description: "Remove visual article block." },
            { name: "list_display_kinds", description: "List component kinds and defaults." },
            { name: "add_display_to_view", description: "Add display to a view." },
            { name: "remove_display_from_view", description: "Remove display from a view." },
            { name: "patch_display_data", description: "Patch a display's data payload." },
            { name: "set_display_order", description: "Reorder displays by id." },
            { name: "analyze_workspace_gaps", description: "Find structure and content gaps." },
            { name: "generate_outline_from_text", description: "Generate outline preview from text." },
            { name: "generate_topic_from_outline", description: "Create topic/view structure from an outline." },
            { name: "infer_component_type", description: "Infer recommended component kind from payload." },
            { name: "import_data_block", description: "Import a data payload and add a component display." },
            { name: "suggest_layout_for_view_mode", description: "Suggest layout mode and supporting displays." },
            { name: "rewrite_view_layout_for_mode", description: "Rewrite a view for a target layout mode." },
            { name: "preview_render_profile", description: "Preview render complexity for a view." },
            { name: "search_semantic", description: "Search with token-based semantic score." },
            { name: "search_workspace", description: "Search notebooks and nested content." },
            { name: "workspace_health_check", description: "Return consistency and integrity issues." },
            { name: "analyze_orphaned_data", description: "List orphan pages, topics, and views." },
            { name: "publish_diagnose", description: "Analyze publish readiness and blockers." },
            { name: "batch_read_workspace", description: "Execute multiple read tools in one call." },
            { name: "batch_mutate_workspace", description: "Execute multiple mutation operations in one call." },
            { name: "validate_after_mutation", description: "Run validation after mutation." },
            { name: "plan_agentic_workflow", description: "Generate an agent workflow with optional prechecks." },
            { name: "task_suggest_and_execute", description: "Suggest and optionally execute task steps." },
            { name: "execute_plan_with_guarantees", description: "Execute a plan with guardrails and validation." },
            { name: "snapshot_compare", description: "Compare notebook state to snapshot-derived state." },
            { name: "diff_notebook_state", description: "Compare notebook structure with snapshot ids." },
            { name: "find_duplicate_or_stale_content", description: "Find duplicate content and stale records." },
            { name: "repair_workspace", description: "Repair workspace consistency and normalize ordering." },
            { name: "repair_workspace_consistency", description: "Remove orphan records and normalize order." },
            { name: "export_notebook", description: "Export notebook as markdown or web HTML." },
            { name: "export_page", description: "Export page as markdown or web HTML." },
            { name: "export_view", description: "Export single view as markdown or web HTML." },
            { name: "export_publish_bundle", description: "Build notebook export bundle for publishing." },
            { name: "snapshot_workspace", description: "Create workspace snapshot for undo/rollback." },
            { name: "list_workspace_snapshots", description: "List workspace snapshots." },
            { name: "restore_workspace_snapshot", description: "Restore workspace from snapshot." },
            { name: "publish_notebook", description: "Set notebook published flag." },
            { name: "unpublish_notebook", description: "Unset notebook published flag." },
            { name: "set_notebook_metadata", description: "Set notebook metadata including editor settings." },
            { name: "agentic_observe_workspace", description: "Get workspace state, health, duplicates, drift, and policy summary for safe agent decisions." },
            { name: "agentic_intent_to_plan", description: "Convert a natural-language goal into a proposed agentic plan." },
            { name: "agentic_plan_dryrun", description: "Simulate a planned sequence and summarize impacted entities." },
            { name: "agentic_plan_guardrail", description: "Validate plan risk and filter unsafe operations." },
            { name: "agentic_execute_with_sla", description: "Execute plan with guardrails and optional SLA enforcement." },
            { name: "agentic_auto_repair", description: "Run a safe repair sequence for structural inconsistencies." },
            { name: "agentic_suggest_restructure", description: "Propose structure changes from semantic and order heuristics." },
            { name: "agentic_reference_rewrite", description: "Analyze unresolved references and propose or apply safe rewrites." },
            { name: "agentic_component_pipeline", description: "Run component/layout evolution steps on a candidate notebook." },
            { name: "agentic_change_set", description: "Preview entity-level delta for a change plan before mutation." },
            { name: "agentic_contract_enforcer", description: "Evaluate contract/policy invariants and return pass/fail posture." },
            { name: "agentic_observation_query", description: "Read filtered agentic observations for planning and debugging." },
            { name: "agentic_workflow_job", description: "Create, reconcile, or execute an agentic workflow job." },
            { name: "agentic_workflow_status", description: "Read status for the latest or a specific workflow job." },
            { name: "agentic_workflow_cancel", description: "Cancel an in-flight workflow job." },
            { name: "agentic_preflight_gate", description: "Run preflight health, guardrail, and optional publish checks." },
            { name: "agentic_plan_optimizer", description: "Optimize and filter a candidate plan before execution." },
            { name: "agentic_plan_reconciler", description: "Reconcile stale ids in a plan against current workspace state." },
            { name: "agentic_goal_expander", description: "Expand a goal into likely sub-goals and suggested tool chains." },
            { name: "agentic_impact_scoper", description: "Estimate scope and risk impact for each planned change." },
            { name: "agentic_multi_notebook_batch", description: "Run multiple notebook batches in one preview or execution call." },
            { name: "agentic_policy_set", description: "List, validate, or run policy checks across workspace scope." },
            { name: "agentic_publish_readiness_gate", description: "Evaluate publish readiness and contract checks across notebooks." },
            { name: "agentic_structured_ingest_from_text", description: "Convert text to structured outline topics and apply when requested." },
            { name: "agentic_component_compatibility_check", description: "Check data payload compatibility against component kinds." },
            { name: "agentic_drift_scheduler", description: "Generate drift and duplicate remediation schedule signals." },
            { name: "agentic_change_set_renderer", description: "Render readable plan summaries from change-set operations." },
            { name: "agentic_tool_feedback", description: "Record feedback from workflow/plan execution for future guidance." },
            { name: "agentic_tool_selector", description: "Suggest best-matching agentic tools for a user goal." },
            { name: "list_mcp_tool_capabilities", description: "List all MCP tools this workspace exposes." },
            { name: "describe_mcp_tool", description: "Describe a specific MCP tool." },
        ] as const,
    })

export const describeMcpTool = (toolName: string): WorkspaceOperationResult<{ name: string; description: string }> => {
    const capabilities = listMcpToolCapabilities()
    if (!capabilities.ok) return capabilities
    const match = capabilities.value.tools.find(tool => tool.name === toolName)
    if (!match) return notFound("Tool not found.")
    return ok(match)
}

export const createVisualArticleBlock = (visualKind: VisualBlockKind, data: VisualBlockData): Extract<ArticleBlock, { kind: "visual" }> => {
    const mergedData = { ...defaultVisualBlockData(visualKind), ...data }
    return {
        kind: "visual",
        visualKind,
        data: mergedData,
        raw: serializeVisualBlockBody(mergedData),
    }
}
